#!/bin/bash

echo "=== BUFFER OVERFLOW TESTS ==="
echo ""
echo "--- safe.c (should have 0 or LOW findings) ---"
./build/SentinelX --source tests/buffer_overflow/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -E "^\[SOURCE\]|^No potential"
echo ""
echo "--- vulnerable.c (should have MANY HIGH/CRITICAL findings) ---"
./build/SentinelX --source tests/buffer_overflow/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""

echo "=== FORMAT STRING TESTS ==="
echo ""
echo "--- safe.c (should have 0-2 findings) ---"
./build/SentinelX --source tests/format_string/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""
echo "--- vulnerable.c (should have MANY findings) ---"
./build/SentinelX --source tests/format_string/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""

echo "=== INTEGER OVERFLOW TESTS ==="
echo ""
echo "--- safe.c (should have 0 findings) ---"
./build/SentinelX --source tests/integer_overflow/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -E "^\[SOURCE\]|^No potential"
echo ""
echo "--- vulnerable.c (should have MANY findings) ---"
./build/SentinelX --source tests/integer_overflow/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""

echo "=== USE AFTER FREE TESTS ==="
echo ""
echo "--- safe.c (should have 0 findings) ---"
./build/SentinelX --source tests/use_after_free/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -E "^\[SOURCE\]|^No potential"
echo ""
echo "--- vulnerable.c (should have MANY findings) ---"
./build/SentinelX --source tests/use_after_free/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""

echo "=== COMMAND INJECTION TESTS ==="
echo ""
echo "--- safe.c (should have 0 findings) ---"
./build/SentinelX --source tests/command_injection/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -E "^\[SOURCE\]|^No potential"
echo ""
echo "--- vulnerable.c (should have MANY findings) ---"
./build/SentinelX --source tests/command_injection/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""

echo "=== RACE CONDITION TESTS ==="
echo ""
echo "--- safe.c (should have 0 findings) ---"
./build/SentinelX --source tests/race_condition/safe.c --all-functions --min-confidence MEDIUM 2>&1 | grep -E "^\[SOURCE\]|^No potential"
echo ""
echo "--- vulnerable.c (should have findings) ---"
./build/SentinelX --source tests/race_condition/vulnerable.c --all-functions --min-confidence MEDIUM 2>&1 | grep -c "\[SOURCE\]"
echo ""
